name: Stale handler
on:
  schedule:
  - cron: 0 0 * * *

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v4.0.0
      id: stale
      with:
        days-before-stale: 28
        days-before-close: 14
        exempt-issue-labels: bug,enhancement
        exempt-pr-labels: bug,enhancement
        stale-issue-label: stale
        stale-pr-label: stale
        stale-issue-message: >-
          This issue is stale because it has been open for 4 weeks with no activity.
          Remove stale label or comment or this will be closed in 2 weeks.
        stale-pr-message: >-
          This pull request is stale because it has been open for 4 weeks with no activity.
          Remove stale label or comment or this will be closed in 2 weeks.
